# Generated by Django 6.0.6 on 2026-07-07 03:30

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PublicationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Publication date')),
                ('publication_type', models.CharField(choices=[('policy', 'Policy'), ('report', 'Report'), ('guideline', 'Guideline')], default='policy', max_length=32)),
                ('office', models.CharField(blank=True, help_text="Owning division or office, e.g. 'Curriculum Development Division'.", max_length=200)),
                ('format', models.CharField(blank=True, default='PDF', help_text="Document format label shown in listings, e.g. 'PDF'.", max_length=20)),
                ('size', models.CharField(blank=True, help_text="Human-readable file size shown in listings, e.g. '3.2 MB'.", max_length=20)),
                ('summary', models.TextField(blank=True, help_text='Short summary shown on the publications index and cards.')),
                ('key_points', wagtail.fields.StreamField([('point', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200})}, help_text="Optional 'at a glance' bullets shown above the body.")),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Main body content. Use H2 headings for section titles.')),
            ],
            options={
                'verbose_name': 'Publication page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
