# Generated by Django 6.0.6 on 2026-07-11 05:30

import django.db.models.deletion
import django.utils.timezone
import modelsearch.index
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('file', models.FileField(help_text='The publication file (PDF, DOCX, etc.).', upload_to='publications/')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Publication date')),
                ('publication_type', models.CharField(choices=[('policy', 'Policy'), ('report', 'Report'), ('guideline', 'Guideline')], default='policy', max_length=32)),
                ('office', models.CharField(blank=True, help_text="Owning division or office, e.g. 'Curriculum Development Division'.", max_length=200)),
                ('summary', models.TextField(blank=True, help_text='Short summary shown on the publications index and cards.')),
                ('key_points', wagtail.fields.StreamField([('point', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200})}, help_text="Optional 'at a glance' bullets shown above the body.")),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Main body content. Use H2 headings for section titles.')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-date'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='PublicationIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
