# Generated by Django 6.0.6 on 2026-07-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from the title if left blank.', max_length=255, unique=True),
        ),
    ]
