# Generated by Django 6.0.6 on 2026-07-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_alter_publication_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='office',
            field=models.CharField(blank=True, choices=[('planning', 'Planning, Coordination & Research Division'), ('strategic', 'Strategic Support Unit'), ('curriculum', 'Curriculum Development Division'), ('asset', 'Asset Management Division')], help_text='Owning division or office.', max_length=32),
        ),
    ]
