# Generated by Django 6.0.6 on 2026-07-11 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_alter_publication_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='newer_entry',
            field=models.ForeignKey(blank=True, help_text='Newer publication that supersedes this one, shown as a link on the frontend.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='publication.publication'),
        ),
    ]
