# Generated by Django 6.0.6 on 2026-07-11 09:24

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_publication_newer_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_publications', to='publication.publication')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='publication.publication')),
            ],
            options={
                'verbose_name': 'Related publication',
                'verbose_name_plural': 'Related publications',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
