# Generated by Django 6.0.6 on 2026-07-07 04:24

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('lead', models.TextField(blank=True, help_text='Short lead paragraph shown in the page header.')),
                ('purpose_heading', models.CharField(blank=True, max_length=200)),
                ('purpose_body', wagtail.fields.RichTextField(blank=True, help_text="Main 'Our purpose' body content.")),
                ('pillars', wagtail.fields.StreamField([('pillar', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {})}, help_text="'Built on three pillars' cards.")),
                ('support_heading', models.CharField(blank=True, max_length=200)),
                ('support_body', models.TextField(blank=True)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('purpose_image', models.ForeignKey(blank=True, help_text='Illustrative image for the purpose section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'About page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
