# Generated by Django 6.0.6 on 2026-07-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_aboutpage_pillars_aboutpage_pillar_one_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='pillar_one_icon',
            field=models.CharField(blank=True, choices=[('shield', 'Shield (verified / trust)'), ('people', 'People (community / inclusion)'), ('cloud', 'Cloud (access / offline)')], max_length=32),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='pillar_three_icon',
            field=models.CharField(blank=True, choices=[('shield', 'Shield (verified / trust)'), ('people', 'People (community / inclusion)'), ('cloud', 'Cloud (access / offline)')], max_length=32),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='pillar_two_icon',
            field=models.CharField(blank=True, choices=[('shield', 'Shield (verified / trust)'), ('people', 'People (community / inclusion)'), ('cloud', 'Cloud (access / offline)')], max_length=32),
        ),
    ]
