# Generated by Django 6.0.6 on 2026-07-23 03:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_aboutpage_pillar_one_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='pillar_one_icon',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='pillar_one_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='pillar_one_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='pillar_three_icon',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='pillar_three_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='pillar_three_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='pillar_two_icon',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='pillar_two_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='pillar_two_title',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='pillars',
            field=wagtail.fields.StreamField([('pillar', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('shield', 'Shield (verified / trust)'), ('people', 'People (community / inclusion)'), ('cloud', 'Cloud (access / offline)')], 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1), ('icon', 2)]], {})}, help_text="'Built on three pillars' cards."),
        ),
    ]
